# Hedge Fund Simulator - Example Configuration
# Save this file as 'config.yaml' and modify as needed

# Market Data Configuration
market_data:
  # List of tickers to trade (e.g., ['AAPL', 'MSFT', 'GOOGL'])
  tickers: ['SPY']
  
  # Date range for backtesting (YYYY-MM-DD format)
  start_date: '2023-01-01'
  end_date: '2023-12-31'
  
  # Data interval: '1d' (daily), '1h' (hourly), '1m' (minute)
  interval: '1d'
  
  # Technical indicators to calculate
  indicators:
    - 'sma'      # Simple Moving Average
    - 'ema'      # Exponential Moving Average
    - 'rsi'      # Relative Strength Index
    - 'macd'     # Moving Average Convergence Divergence
    - 'bbands'   # Bollinger Bands
    - 'atr'      # Average True Range
    - 'obv'      # On-Balance Volume
    - 'stoch'    # Stochastic Oscillator

# Quantitative Strategy Configuration
quant:
  # Strategy to use (e.g., 'moving_average_crossover', 'mean_reversion')
  strategy: 'moving_average_crossover'
  
  # Moving Average Crossover parameters
  fast_ma: 10       # Fast moving average period
  slow_ma: 30       # Slow moving average period
  
  # RSI parameters
  rsi_period: 14    # RSI lookback period
  rsi_overbought: 70 # RSI overbought threshold
  rsi_oversold: 30   # RSI oversold threshold
  
  # MACD parameters
  macd_fast: 12     # MACD fast period
  macd_slow: 26     # MACD slow period
  macd_signal: 9    # MACD signal period
  
  # Position sizing
  position_size: 0.1 # Fraction of portfolio to allocate per trade (0.1 = 10%)

# Risk Management Configuration
risk:
  # Position sizing
  max_position_size: 0.2       # Maximum position size as % of portfolio
  max_portfolio_risk: 0.02     # Maximum risk per trade as % of portfolio
  
  # Stop loss and take profit
  stop_loss_pct: 0.05          # 5% stop loss
  take_profit_pct: 0.10        # 10% take profit
  trailing_stop: 0.03          # 3% trailing stop (0 to disable)
  
  # Volatility-based position sizing
  use_volatility_scaling: true
  volatility_lookback: 21       # Lookback period for volatility calculation (in days)
  target_volatility: 0.20      # Target annualized volatility (20%)
  
  # Maximum drawdown protection
  max_drawdown: 0.20           # 20% maximum drawdown before reducing position sizes

# Portfolio Management Configuration
portfolio:
  initial_cash: 100000         # Initial capital in USD
  max_positions: 5             # Maximum number of open positions
  
  # Transaction costs
  commission_pct: 0.001        # 0.1% commission per trade
  slippage_pct: 0.0005         # 0.05% slippage per trade
  
  # Rebalancing
  rebalance_frequency: 'W'      # 'D'=daily, 'W'=weekly, 'M'=monthly
  
  # Cash management
  min_cash_balance: 0.05       # Minimum cash balance as % of portfolio (5%)
  
  # Position limits
  max_sector_exposure: 0.30    # Maximum exposure to any single sector (30%)
  max_asset_correlation: 0.70  # Maximum allowed correlation between assets

# Backtest Configuration
backtest:
  output_dir: 'backtest_results'  # Directory to save results
  save_plots: true               # Save performance plots
  show_plots: false              # Show plots interactively (may not work in all environments)
  save_trades: true             # Save detailed trade log
  
  # Performance metrics
  risk_free_rate: 0.05           # Annual risk-free rate (5%)
  benchmark: 'SPY'               # Benchmark for comparison
  
  # Walk-forward analysis
  walk_forward: false            # Enable walk-forward optimization
  optimization_window: 252        # Optimization window in days (1 year)
  testing_window: 63             # Testing window in days (3 months)
  
  # Monte Carlo simulation
  monte_carlo: false             # Enable Monte Carlo simulation
  num_simulations: 1000          # Number of simulations to run
  confidence_level: 0.95         # Confidence level for VaR/CVaR

# OpenAI Integration (Optional)
openai:
  enabled: false                 # Set to true to enable OpenAI features
  api_key: ''                    # Your OpenAI API key (store in .env file instead)
  
  # Sentiment analysis
  analyze_news: false            # Enable news sentiment analysis
  news_sources:                  # News sources to analyze
    - 'bloomberg'
    - 'reuters'
    - 'wsj'
  
  # Trade explanations
  explain_trades: false          # Generate natural language trade explanations
  
  # Strategy generation
  generate_strategies: false     # Enable strategy generation from descriptions
  default_model: 'gpt-3.5-turbo' # Default model to use

# Logging Configuration
logging:
  level: 'INFO'                 # Log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: 'hedgefund_simulator.log' # Log file path (empty for console only)
  max_size: 10485760            # Max log file size in bytes (10MB)
  backup_count: 5               # Number of backup logs to keep

# Email Notifications (Optional)
email:
  enabled: false
  smtp_server: 'smtp.example.com'
  smtp_port: 587
  username: 'your-email@example.com'
  password: ''                  # Store in environment variable
  from_addr: 'your-email@example.com'
  to_addrs: ['recipient@example.com']
  
  # Notification settings
  send_on_completion: true
  send_on_error: true
  max_attachment_size: 5242880   # 5MB

# Example of a custom strategy configuration
custom_strategies:
  mean_reversion:
    lookback_period: 14
    entry_zscore: 2.0
    exit_zscore: 0.0
    
  trend_following:
    entry_ma: 50
    exit_ma: 200
    atr_multiplier: 2.0
    
  breakout:
    lookback_period: 20
    atr_multiplier: 1.5
    min_volume_multiplier: 1.5
